### ISSUE TITLE
util:RemoveFolderEx

### ISSUE THREAD

**Issue by alicera** [kurtanr/WiXInstallerExamples#15] opened 2022-11-09 23:54 UTC
https://www.hass.de/content/wix-how-use-removefolderex-your-xml-scripts

I follow this to remove program.
After install the program with msi, I add some file into the folder.
Then I remove it with msi , the files that I add still exist.
It can not be removed. 
Do you know why? 
 thank

**Comment by kurtanr** [comment] 2022-11-10 15:48
Hello @alicera,

without some sample code it is difficult to say what the problem is.

Remarks at https://wixtoolset.org/documentation/manual/v3/xsd/util/removefolderex.html suggest that:
- "for a typical use case of removing a folder during uninstall is to write the directory path to the registry and to load it during uninstall" (using [RememberPropertyPattern](https://github.com/kurtanr/WiXInstallerExamples/tree/main/06_RememberPropertyPatternComplete))

In the sample article you linked `APPLICATIONFOLDER` was indeed read from registry. Are you doing the same?

Alternatively, if you just want to delete some files and not the entire folder, you can instead use https://wixtoolset.org/documentation/manual/v3/xsd/wix/removefile.html

**Comment by alicera** [comment] 2022-11-11 08:17
hi @kurtanr
Thanks for  your reply.

I try install it with msi and create a folder 0 by myself
Then remove the app, the folder can not clear up.
There is a 0 folder exist

Here is the code that I reproduce and I reference this
https://www.hass.de/content/wix-how-use-removefolderex-your-xml-scripts
https://www.codeproject.com/Tips/105638/A-quick-introduction-Create-an-MSI-installer-with



you can get the icon with https://www.codeproject.com/favicon.ico
I create the example.exe (fake). 

I build it with the command
```
"C:/Program Files (x86)/WiX Toolset v3.11/bin/candle.exe" -ext WixUtilExtension example.wxs && "C:/Program Files (x86)/WiX Toolset v3.11/bin/light.exe" -ext WixUtilExtension example.wixobj
```


example.wxs
```
<?xml version="1.0"?>
<?define ProductVersion = "0.0.1"?>
<?define ProductUpgradeCode = "12345678-1234-1234-1234-111111111111"?>
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi"
  xmlns:util="http://schemas.microsoft.com/wix/UtilExtension">
   <Product Id="*" UpgradeCode="$(var.ProductUpgradeCode)" 
            Name="Example Product Name" Version="$(var.ProductVersion)" Manufacturer="Example Company Name" Language="1033">
      <Package InstallerVersion="200" Compressed="yes" Comments="Windows Installer Package"/>
      <Media Id="1" Cabinet="product.cab" EmbedCab="yes"/>
      <Icon Id="ProductIcon" SourceFile="favicon.ico"/>
      <Property Id="ARPPRODUCTICON" Value="ProductIcon"/>
      <Property Id="ARPHELPLINK" Value="http://www.exampleproduct.com"/>
      <Property Id="ARPURLINFOABOUT" Value="http://www.examplecompany.com"/>
      <Property Id="ARPNOREPAIR" Value="1"/>
      <Property Id="ARPNOMODIFY" Value="1"/>
      <Upgrade Id="$(var.ProductUpgradeCode)">
         <UpgradeVersion Minimum="$(var.ProductVersion)" OnlyDetect="yes" Property="NEWERVERSIONDETECTED"/>
         <UpgradeVersion Minimum="0.0.0" Maximum="$(var.ProductVersion)" IncludeMinimum="yes" IncludeMaximum="no" 
                         Property="OLDERVERSIONBEINGUPGRADED"/>	  
      </Upgrade>
      <Condition Message="A newer version of this software is already installed.">NOT NEWERVERSIONDETECTED</Condition>




      <Property Id="APPLICATIONFOLDER">
        <RegistrySearch Key="Software\Example Company Name\Example Product Name" Root="HKLM" Type="raw" Id="APPLICATIONFOLDER_REGSEARCH" Name="Path" />
      </Property>


      <Directory Id="TARGETDIR" Name="SourceDir">
         <Directory Id="ProgramFilesFolder">
            <Directory Id="INSTALLDIR" Name="Example">
               <Component Id="ApplicationFiles" Guid="12345678-1234-1234-1234-222222222222">
                  <File Id="ApplicationFile1" Source="example.exe"/>
               </Component>
            </Directory>
         </Directory>

         <Directory Id="ProgramMenuFolder">
            <Directory Id="ProgramMenuSubfolder" Name="Example">
               <Component Id="ApplicationShortcuts" Guid="12345678-1234-1234-1234-333333333333">
                  <Shortcut Id="ApplicationShortcut1" Name="Example Shortcut Name" Description="Example Product Name" 
                            Target="[INSTALLDIR]example.exe" WorkingDirectory="INSTALLDIR"/>
                  <RegistryValue Root="HKCU" Key="Software\Example Company Name\Example Product Name" 
                            Name="installed" Type="integer" Value="1" KeyPath="yes"/>
                  <RemoveFolder Id="ProgramMenuSubfolder" On="uninstall"/>
               </Component>
            <Component Id="CleanupMainApplicationFolder" Guid="0ffde969-e17c-4708-a7fd-3e0dfacab6b0">
                <RegistryValue Root="HKCU" Key="Software\Example Company Name\Example Product Name" Name="Path" Type="string" Value="[APPLICATIONFOLDER]" KeyPath="yes" />
                <!-- We need to use APPLICATIONFOLDER variable here or RemoveFolderEx
                        will not remove on "install". -->
                <util:RemoveFolderEx On="uninstall" Property="APPLICATIONFOLDER" />
            </Component>
            </Directory>
         </Directory>
      </Directory>



        
      <InstallExecuteSequence>
         <RemoveExistingProducts After="InstallValidate"/>
      </InstallExecuteSequence>

      <Feature Id="DefaultFeature" Level="1">
         <ComponentRef Id="ApplicationFiles"/>
         <ComponentRef Id="ApplicationShortcuts"/>		 
           <ComponentRef Id="CleanupMainApplicationFolder" />

      </Feature>
   </Product>
</Wix>
```





install it with msi and create a folder 0 by myself
![image](https://user-images.githubusercontent.com/59388989/201295843-b41f2bd4-67e8-4e6e-8f16-9ebb8f0dd9aa.png)
_
uninstall it 
![image](https://user-images.githubusercontent.com/59388989/201295964-5a1319a8-2bfd-452c-bc31-48a625d30e14.png)


0 exist , not remove
![image](https://user-images.githubusercontent.com/59388989/201296294-f68c3d41-3557-4f5a-badd-8331cce097a2.png)

**Comment by kurtanr** [comment] 2022-11-12 19:15
Hello @alicera,

one thing I've noticed is that `RegistrySearch` targets `Root="HKLM"` and in `RegistryValue` you are targeting `Root="HKCU"`.

Also, your code does not really follow the example from https://www.hass.de/content/wix-how-use-removefolderex-your-xml-scripts where XML structure is quite different (e.g. `RemoveFolderEx` is under the `DirectoryRef` component).

I also suggest you install / uninstall the installer with logging enabled (`/L*V`) and you should get more information regarding the problem.

**Comment by alicera** [comment] 2022-11-13 00:42
1. Can I use the Root="HKCU" to RegistryValue ( installed path )  not  Root="HKLM" ?
2.   https://www.hass.de/content/wix-how-use-removefolderex-your-xml-scripts  the sample have some problem, (1) The "APPLICATIONFOLDER" of `    <util:RemoveFolderEx On="install" Property="APPLICATIONFOLDER" /> is reference from A or B ?

A : <Property Id="APPLICATIONFOLDER">
B:<DirectoryRef Id="APPLICATIONFOLDER">

**Comment by alicera** [comment] 2022-11-13 00:43
```
A <Property Id="APPLICATIONFOLDER">

B <DirectoryRef Id="APPLICATIONFOLDER">

```

**Comment by kurtanr** [comment] 2022-11-14 20:27
Hello @alicera,

1. Both HKCU and HKLM are fine - the important thing is that you use the same one both in `RegistrySearch` and in `RegistryValue`.
2. Don't think the linked example is wrong - I saw similar code samples in other places also.

Anyway, since this issue is not really related to any of the examples / articles in this repository, I am closing the issue.

**Closed as completed by kurtanr** 2022-11-14 20:27 UTC

**Comment by alicera** [comment] 2022-11-16 14:08
Thanks your help

Do you meet the status?
When I upgrade my program with wix, I found the   <util:RemoveFolderEx On="uninstall" Property="INSTALLDIR" />  will remove the folder.

I expect the uninstall step not the upgrade. 

Do you have any idea?

**Comment by kurtanr** [comment] 2022-11-16 15:39
Hello @alicera,

during [major upgrade](https://wixtoolset.org/docs/v3/xsd/wix/majorupgrade/) previous version of the application if first uninstalled and then the new version is installed ('Schedule' property has some more information about that). This is why folders are deleted on upgrade.

**Comment by alicera** [comment] 2022-11-17 08:20
I reference the major upgrade.
I set Schedule as afterInstallInitialize.

At the same condition, I try to use 
```
<RemoveFile Id="FILE" Directory="log" Name ="*.*" On ="uninstall"/>
<RemoveFolder Id="FOLDER" Directory="log" On="uninstall"/>
```
and
```
<util:RemoveFolderEx On="uninstall" Property="INSTALLDIR"/> 
```

The util:RemoveFolderEx will be trigger  when  uninstall and upgrade.
The  RemoveFolder and RemoveFile will be trigger when uninstall.
